### PR TITLE
Issue: DNS dns-hijack not work at macos

### PR DESCRIPTION
**Pull request by fishg**
test on these config:
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:8053
  enhanced-mode: redir-host

tun:
  enable: true
  stack: system #gvisor
  dns-hijack:
    - 0.0.0.0:53
  auto-route: true

### CODE REVIEW

**Comment by yaling888** [comment]
What's your system dns address? these private address (127/8) (10/8) (172.16/12) (192.168/16) are not set in the routing table, please set a public IP in your system dns.

**Comment by fishg** [comment]
understand,should not use lan gateway ip. change to public dns ip it’s work.

**Comment by yaling888** [comment]
It means that private traffic also can't pass through the TUN adapter.

**Comment by yaling888** [comment]
You can add this route `sudo route add -inet 0.0.0.0/0 -interface utun` in system routing table by manually.

**Pull request closed without merging**
